### PR TITLE
Ian docs

### PR DESCRIPTION
**Pull request by ifranda**
Three changes:
* Update contributing to documentation guide
* Replace examples with link to Pythia cookbook
* Short paragraph on util functions

If it helps, I edited these five files:
* README
* config.py
* docs/pythonAPIReference/examples.rst
* docs/contributingToVapor/contributingToVaporsDocumentation.rst
* docs/contributingToVapor/codeContributions.rst

Let me know if anything doesn't make sense or if something went wrong! It looks like there are a lot more line removals than line additions -- not sure if that's a sign that something went wrong...

### CODE REVIEW

**Review by sgpearse — CHANGES_REQUESTED** [review]
Could you add an example of these changes?  The Markdown on github is messing up the .rst formatting, but something like what is below might help.  Users will also need to install the Doxygen documentation generator before step 4.

- Editing <home>/VAPOR/apps/pythonapi/vapor/session.py using Python syntax
```
   ...
   def NewRenderer(self, Class:Renderer, datasetName:str) -> Renderer:
   # Here is my new comment
   ...
```


- Editing <home>/VAPOR/include/vapor/RenderParams.h using C++ and Doxygen syntax
```
   ...
   //! Here is my new comment
   virtual int Initialize();
   ...
```

**Comment by ifranda** [comment]
Great suggestions! I'll add some updates tomorrow.

**Comment by ifranda** [comment]
> Users will also need to install the Doxygen documentation generator before step 4.

I don't think I had to manually install Doxygen on my Mac or WSL Ubuntu -- maybe it's installed as a dependency for Vapor-python?

**Review by sgpearse — APPROVED** [review]

**Comment by sgpearse** [comment]
> I don't think I had to manually install Doxygen on my Mac or WSL Ubuntu -- maybe it's installed as a dependency for Vapor-python?

Ah, that would make sense.  Thanks Ian!

**Pull request merged**
